export const FACTS: string[] = [
  'The first computer bug was an actual moth found in the Harvard Mark II in 1947.',
  'Python was named after Monty Python\'s Flying Circus, not the snake.',
  'The first programmer was Ada Lovelace, who wrote algorithms for Charles Babbage\'s Analytical Engine in 1843.',
  'Git can be used as a rudimentary database if you\'re brave enough.',
  'The "sizeof" operator in C was originally a compiler directive, not a function.',
  'There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.',
  'The first computer virus for DOS was called "Brain" and was created by two brothers in 1986.',
  'Java\'s mascot "Duke" was created by Joe Palrang, who also worked on Shrek.',
  'The "404 Not Found" error code was inspired by room 404 at CERN where the World Wide Web was developed.',
  'JavaScript was created in just 10 days by Brendan Eich in 1995.',
  'The QWERTY keyboard was designed to slow you down so typewriters wouldn\'t jam.',
  'The first hard drive could only store 5MB and weighed over a ton.',
  'Linux was created by Linus Torvalds in 1991 as a hobby project.',
  'The "@" symbol used in emails was chosen by Ray Tomlinson because it meant "at" and was rarely used.',
  'The first website is still online: info.cern.ch.',
  'C++ was originally called "C with Classes".',
  'The CAPTCHA test was created by Luis von Ahn, who later co-founded Duolingo.',
  'Stack Overflow was created by Jeff Atwood and Joel Spolsky in 2008.',
  'The first computer game was "Spacewar!" created in 1962 at MIT.',
  'Ruby on Rails was extracted from Basecamp by David Heinemeier Hansson in 2005.',
  'Docker containers share the host OS kernel, making them lighter than VMs.',
  'The term "software engineer" was first used in the 1960s by Margaret Hamilton during Apollo missions.',
  'TypeScript was released by Microsoft in 2012, created by Anders Hejlsberg (also creator of C#).',
  'The first microprocessor, Intel 4004, had 2,300 transistors. Modern CPUs have billions.',
  'Vim has a built-in tutorial accessible by running "vimtutor" in your terminal.',
  'SQL was originally called SEQUEL, but was renamed due to trademark issues.',
  'The famous "Hello, World!" program originated from Brian Kernighan\'s 1978 book.',
  'Google processes over 99,000 search queries every second.',
  'The first domain name ever registered was symbolics.com on March 15, 1985.',
  'Fortran is the oldest programming language still in active use (1957).',
  'Ctrl + C to copy was popularized by Apple (using Command + C) and later adopted by Windows.',
  'The first electronic computer, ENIAC, occupied 1,800 square feet and consumed 150kW of power.',
  'A single Amazon AWS region can have more computing power than the entire internet of 2002.',
  'The term "refactoring" was coined by Martin Fowler and Kent Beck in their 1999 book.',
  'GraphQL was developed internally at Facebook in 2012 before being open-sourced in 2015.',
  'React was created by Jordan Walke, a Facebook engineer, in 2011.',
  'The NPM registry is the largest package registry in the world, with over 2 million packages.',
  'Kubernetes was built based on Google\'s internal system Borg, which managed billions of containers.',
  'The first electronic spreadsheet, VisiCalc, helped launch the personal computer revolution.',
  'The "while" loop in Python uses "else" clause that runs only if the loop completed without break.',
  'The worst code is the code you wrote six months ago that now looks like someone else wrote it.',
  '"It works on my machine" is the most famous developer excuse — and it\'s usually true.',
  'A developer\'s blood caffeine content is directly proportional to their productivity. Science hasn\'t confirmed this yet.',
  'CSS: The only language where you center a div and the div says "nah, I\'ll stay left."',
  'The best way to debug your code is to explain it to a rubber duck. No, really, it works.',
  'There are 10 types of people in the world: those who understand binary, and those who don\'t.',
  'The compiler is your friend. The linter is your strict parent.',
  'Indenting with spaces vs tabs: the war that will never end.',
  'Production is where code goes to die — and occasionally, where careers go to end.',
  'The first 90% of the code takes 90% of the time. The remaining 10% takes the other 90% of the time.',
  'A good commit message tells you *what* and *why*. A bad one tells you NOTHING.',
  'Every time you use "any" in TypeScript, a puppy cries somewhere.',
  'Recursion: see Recursion.',
  'Regex: you now have two problems.',
  'Vim users spend 30% of their time editing and 70% of their time talking about using Vim.',
  'Your tests are not flaky. Your code is.',
  'If at first you don\'t succeed, call it version 1.0.',
  'Real programmers count from 0.',
  'sudo rm -rf / is the digital equivalent of "hold my beer".',
  'The cloud is just someone else\'s computer.',
  'There is no place like 127.0.0.1.',
  'Fixed 99 bugs in the code, fixed 99 bugs. Take one down, patch it around, 117 bugs in the code.',
];
