import { askUserTool } from './implementations/askUser';
import { findSymbolTool, getDefinitionTool, getReferencesTool, semanticSearchTool } from './implementations/codeIntel';
import { applyRefactorTool, formatCodeTool, getDiagnosticsTool, runLinterTool, runTestsTool, typeCheckTool } from './implementations/devTools';
import { executeBashTool } from './implementations/executeBash';
import { copyFileTool, deleteFileTool, editFileTool, fileInfoTool, findFilesTool, makeDirTool, renameFileTool } from './implementations/filesystemExtra';
import { gitCommitTool, gitCreateBranchTool, gitDiffTool, gitLogTool, gitStatusTool } from './implementations/gitTools';
import { globTool } from './implementations/globTool';
import { checkJobTool, executeLongRunningTool, killJobTool, readOutputTool } from './implementations/jobs';
import { listDirTool } from './implementations/listDir';
import { recallTool, rememberTool, summarizeContextTool, taskNotesTool } from './implementations/memory';
import { readFileTool } from './implementations/readFile';
import { searchFilesTool } from './implementations/searchFiles';
import { generateComponentTool } from './implementations/generateComponent';
import { spawnAgentsTool, getAgentTypesTool, dispatchSubtasksTool } from './implementations/spawnAgents';
import { strReplaceTool } from './implementations/strReplace';
import { suggestFollowupsTool } from './implementations/suggestFollowups';
import { doneTool, showDiffTool } from './implementations/uxTools';
import { fetchUrlTool, apifyScrapeTool, readGithubFileTool, readGithubIssueTool, webSearchTool } from './implementations/webTools';
import { writeFileTool } from './implementations/writeFile';
import { revertChangesTool } from './implementations/revertChanges';
import { dockerizeTool } from './implementations/dockerize';
import { securityScanTool } from './implementations/securityScan';
import { analyzeDependenciesTool } from './implementations/analyzeDependencies';
import { detectCodeSmellsTool } from './implementations/detectCodeSmells';
import { generateTestsTool } from './implementations/generateTests';
import { explainCodeTool } from './implementations/explainCode';
import { migrateCodeTool } from './implementations/migrateCode';
import { writeTodosTool } from './implementations/writeTodos';
import { createGetToolDefinitionsTool } from './implementations/toolDefinitions';
import { ToolRegistry } from './registry';

export function createDefaultRegistry(): ToolRegistry {
  const registry = new ToolRegistry();
  registry.register(readFileTool);
  registry.register(writeFileTool);
  registry.register(editFileTool);
  registry.register(deleteFileTool);
  registry.register(renameFileTool);
  registry.register(executeBashTool);
  registry.register(listDirTool);
  registry.register(makeDirTool);
  registry.register(copyFileTool);
  registry.register(fileInfoTool);
  registry.register(searchFilesTool);
  registry.register(findFilesTool);
  registry.register(findSymbolTool);
  registry.register(getDefinitionTool);
  registry.register(getReferencesTool);
  registry.register(semanticSearchTool);
  registry.register(executeLongRunningTool);
  registry.register(checkJobTool);
  registry.register(killJobTool);
  registry.register(readOutputTool);
  registry.register(rememberTool);
  registry.register(recallTool);
  registry.register(taskNotesTool);
  registry.register(summarizeContextTool);
  registry.register(webSearchTool);
  registry.register(apifyScrapeTool);
  registry.register(fetchUrlTool);
  registry.register(readGithubIssueTool);
  registry.register(readGithubFileTool);
  registry.register(runTestsTool);
  registry.register(runLinterTool);
  registry.register(typeCheckTool);
  registry.register(formatCodeTool);
  registry.register(getDiagnosticsTool);
  registry.register(applyRefactorTool);
  registry.register(gitStatusTool);
  registry.register(gitDiffTool);
  registry.register(gitCommitTool);
  registry.register(gitLogTool);
  registry.register(gitCreateBranchTool);
  registry.register(askUserTool);
  registry.register(generateComponentTool);
  registry.register(showDiffTool);
  registry.register(doneTool);
  registry.register(strReplaceTool);
  registry.register(writeTodosTool);
  registry.register(suggestFollowupsTool);
  registry.register(globTool);
  registry.register(spawnAgentsTool);
  registry.register(getAgentTypesTool);
  registry.register(dispatchSubtasksTool);
  registry.register(revertChangesTool);
  registry.register(dockerizeTool);
  registry.register(securityScanTool);
  registry.register(analyzeDependenciesTool);
  registry.register(detectCodeSmellsTool);
  registry.register(generateTestsTool);
  registry.register(explainCodeTool);
  registry.register(migrateCodeTool);
  registry.register(createGetToolDefinitionsTool(registry));
  return registry;
}
